server:
  port: 8080
  servlet:
    context-path: /iotsite

spring:
  application:
    name: iotsite

  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://39.106.66.219:3306/smart_db?useSSL=false&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

shiro-redis:
  enabled: true
  redis-manager:
    host: 127.0.0.1:6379

iotsite:
  jwt:
    secret: f4e2e52034348f86b67cde581c0f9eb5
    expire: 604800
    header: token